spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.45.204.95:3306/bit701?serverTimezone=Asia/Seoul
    username: lekahelis
    password: bit123!@#
  servlet:
    multipart:
      max-file-size:
        4MB
  mail:
    host: smtp.naver.com
    port: 465
    username: 'helloa1109@naver.com'
    password: 'piano1247@'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
  #mybatis
mybatis:
  type-aliases-package: com.bitnc4.dto
  mapper-locations:
  - /mapper/**/*.xml
